import 'dotenv/config'

export const env = {
  MONGODB_URI: process.env.MONGODB_URI,

  FRONT_END_URL: process.env.FRONT_END_URL,

  APP_HOST: process.env.APP_HOST,
  APP_PORT: process.env.APP_PORT,

  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_ACCESS_KEY: process.env.JWT_ACCESS_KEY,
  JWT_REFRESH_KEY: process.env.JWT_REFRESH_KEY,

  BUCKET_NAME: process.env.BUCKET_NAME,
  KEYFILENAME: process.env.KEYFILENAME,

  API_ENDPOINT_CCCD: process.env.API_ENDPOINT_CCCD,
  API_KEY_CCCD: process.env.API_KEY_CCCD,

  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASS: process.env.EMAIL_PASS,

  API_KEY_TOURIST: process.env.API_KEY_TOURIST,
  API_KEY_GENIMI: process.env.API_KEY_GENIMI,

  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
  GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS
}
